### PR TITLE
Decrease steel trap damage and increase root duration and increase concussion mine damage

### PR DESCRIPTION
**Pull request by novalderya**
Logic : Decrease overall Junkrat damage to decrease trap damage so that if someone with 90 walk in it he will not die instead of an implementation with healing. Then increase all other ability damage 
junk
fixes https://github.com/MaxwellJung/ow1_emulator/issues/189

### CODE REVIEW

**Comment by novalderya** [comment]
fixes #189

**Comment by novalderya** [comment]
fixes #99 
Increase Junkrat concussion mine

If damage 30 : 
(30 - 30 ) / (110 - 30 ) * (120 - 110) = 0

If damage 110 :
(110 - 30)/(110 - 30) * (120 - 110) = 10
junk_concussion_mine

In reality it lacks ~0.94 damage done

**Comment by MaxwellJung** [comment]
Does this implementation also account for melee damage and ultimate damage or do you have to code that in seperately?

**Comment by novalderya** [comment]
> Does this implementation also account for melee damage and ultimate damage or do you have to code that in seperately?

Tested melee does 30 and ultimate one shot a hog so it should be okay

**Comment by novalderya** [comment]
I added one damage in the end to enable the trap concussion mine combo else the hero will have 0.94 hp remaining

**Comment by novalderya** [comment]
Closed due to a problem with my local staging which created some problem to keep clean commits

**Pull request closed without merging**
